// Mock data for AyuDost Dashboard
import { User, Task, Activity, Milestone } from './types';

export const mockUsers: User[] = [
  {
    id: '1',
    name: 'Sanath K',
    email: 'sanath@ayudost.com',
    role: 'Team Leader',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sanath',
    skills: ['Project Management', 'Documentation', 'Testing'],
  },
  {
    id: '2',
    name: 'Rajath Kiran A',
    email: 'rajath@ayudost.com',
    role: 'Backend',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rajath',
    skills: ['Node.js', 'Database', 'API Design'],
  },
  {
    id: '3',
    name: 'Rithesh',
    email: 'rithesh@ayudost.com',
    role: 'AI/ML',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Rithesh',
    skills: ['Machine Learning', 'Python', 'TensorFlow'],
  },
  {
    id: '4',
    name: 'Sheethal D Rai',
    email: 'sheethal@ayudost.com',
    role: 'Frontend',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Sheethal',
    skills: ['React', 'UI/UX', 'Tailwind CSS'],
  },
  {
    id: '5',
    name: 'Prof. Mohan A R',
    email: 'mohan@ayudost.com',
    role: 'Stakeholder',
    avatar: 'https://api.dicebear.com/7.x/avataaars/svg?seed=Mohan',
    skills: ['Project Guidance', 'Research'],
  },
];

export const mockTasks: Task[] = [
  {
    id: '1',
    title: 'Setup Supabase Authentication',
    description: 'Implement user authentication with email/password and Google OAuth',
    status: 'In Progress',
    priority: 'High',
    assigneeId: '2',
    dueDate: '2025-10-31',
    module: 'Authentication',
    subtasks: [
      { id: '1-1', title: 'Configure Supabase project', completed: true },
      { id: '1-2', title: 'Implement email auth', completed: true },
      { id: '1-3', title: 'Add Google OAuth', completed: false },
    ],
    createdAt: '2025-10-15',
    updatedAt: '2025-10-22',
  },
  {
    id: '2',
    title: 'Design Dashboard UI',
    description: 'Create responsive dashboard layout with KPI cards and charts',
    status: 'Completed',
    priority: 'High',
    assigneeId: '4',
    dueDate: '2025-10-20',
    module: 'UI/UX',
    subtasks: [
      { id: '2-1', title: 'Create wireframes', completed: true },
      { id: '2-2', title: 'Build component library', completed: true },
      { id: '2-3', title: 'Implement responsive design', completed: true },
    ],
    createdAt: '2025-10-10',
    updatedAt: '2025-10-20',
  },
  {
    id: '3',
    title: 'Train AI Model for Symptom Analysis',
    description: 'Develop ML model for analyzing user symptoms and providing recommendations',
    status: 'In Review',
    priority: 'High',
    assigneeId: '3',
    dueDate: '2025-11-05',
    module: 'AI/ML',
    subtasks: [
      { id: '3-1', title: 'Collect training data', completed: true },
      { id: '3-2', title: 'Train model', completed: true },
      { id: '3-3', title: 'Test accuracy', completed: false },
    ],
    createdAt: '2025-10-08',
    updatedAt: '2025-10-22',
  },
  {
    id: '4',
    title: 'Database Schema Design',
    description: 'Design and implement database schema for user data and health records',
    status: 'Completed',
    priority: 'High',
    assigneeId: '2',
    dueDate: '2025-10-18',
    module: 'Database',
    subtasks: [
      { id: '4-1', title: 'Define entities', completed: true },
      { id: '4-2', title: 'Create migrations', completed: true },
      { id: '4-3', title: 'Seed test data', completed: true },
    ],
    createdAt: '2025-10-05',
    updatedAt: '2025-10-18',
  },
  {
    id: '5',
    title: 'API Documentation',
    description: 'Write comprehensive API documentation for all endpoints',
    status: 'Pending',
    priority: 'Medium',
    assigneeId: '1',
    dueDate: '2025-11-10',
    module: 'Documentation',
    subtasks: [
      { id: '5-1', title: 'Document auth endpoints', completed: false },
      { id: '5-2', title: 'Document health endpoints', completed: false },
    ],
    createdAt: '2025-10-20',
    updatedAt: '2025-10-20',
  },
  {
    id: '6',
    title: 'Implement Task Board Features',
    description: 'Build Kanban board with drag-and-drop functionality',
    status: 'In Progress',
    priority: 'Medium',
    assigneeId: '4',
    dueDate: '2025-10-28',
    module: 'UI/UX',
    subtasks: [
      { id: '6-1', title: 'Setup react-dnd', completed: true },
      { id: '6-2', title: 'Create task cards', completed: false },
    ],
    createdAt: '2025-10-18',
    updatedAt: '2025-10-22',
  },
  {
    id: '7',
    title: 'AI Report Generator',
    description: 'Build AI-powered report generation for stakeholders',
    status: 'Pending',
    priority: 'Medium',
    assigneeId: '3',
    dueDate: '2025-11-15',
    module: 'AI/ML',
    subtasks: [],
    createdAt: '2025-10-22',
    updatedAt: '2025-10-22',
  },
  {
    id: '8',
    title: 'Unit Testing Suite',
    description: 'Write comprehensive unit tests for all modules',
    status: 'Pending',
    priority: 'Low',
    assigneeId: '1',
    dueDate: '2025-11-20',
    module: 'Testing',
    subtasks: [],
    createdAt: '2025-10-22',
    updatedAt: '2025-10-22',
  },
];

export const mockActivities: Activity[] = [
  {
    id: '1',
    userId: '3',
    action: 'completed task',
    taskId: '3',
    timestamp: '2025-10-22T10:30:00Z',
  },
  {
    id: '2',
    userId: '4',
    action: 'updated task',
    taskId: '6',
    timestamp: '2025-10-22T09:15:00Z',
  },
  {
    id: '3',
    userId: '2',
    action: 'commented on task',
    taskId: '1',
    timestamp: '2025-10-22T08:45:00Z',
  },
  {
    id: '4',
    userId: '1',
    action: 'created task',
    taskId: '7',
    timestamp: '2025-10-22T08:00:00Z',
  },
];

export const mockMilestones: Milestone[] = [
  {
    id: '1',
    title: 'Presentation 1',
    date: '2025-11-01',
    completed: false,
  },
  {
    id: '2',
    title: 'Mid-term Review',
    date: '2025-11-15',
    completed: false,
  },
  {
    id: '3',
    title: 'Final Report',
    date: '2025-12-10',
    completed: false,
  },
  {
    id: '4',
    title: 'Project Demo',
    date: '2025-12-15',
    completed: false,
  },
];

export const modules = [
  'Authentication',
  'Database',
  'AI/ML',
  'UI/UX',
  'Documentation',
  'Testing',
];
